spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    devtools:
      restart:
        enabled: true

    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 4
        host: 123.207.86.66
        port: 6379
        password: xie123@...       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        topic: __keyevent@0__:expired
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
#cache config
    cache:
         type: redis

#文件请求设置
    http:
        multipart:
           enabled: true
           max-request-size: 100MB
           max-file-size: 100MB

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.plusesb.entity
  typeEnumsPackage: com.plusesb.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
venice:
    jwt:
        # 加密秘钥
        secret: f4e2e52034348f86b67cde581c0f9eb5
        # token有效时长，7天，单位秒
        expire: 604800
        header: token
#静态前缀
    cdn:
        domain:
          upload: http://venice-test-bucket.oss-cn-beijing.aliyuncs.com
#logging:
#  level: warn
logging:
  level:
    com.plusesb.mapper: debug

